### ISSUE TITLE
Investigate broken build

### ISSUE THREAD

**Issue by taDachs** [pse-parkview/PSE_dashboard#118] opened 2021-12-06 14:22 UTC
Our build broke, apparently with the release of node 16. This lead to a couple of weird behaviour, including not creating the `dist/frontend` folder when running `npm run build` and breaking the docker build by extension. 

I psuhed a hacky solution that should fix it, but I don't trust hacky solutions and would prefer some explanation

- [x] why did it break
- [ ] how can we reuse our action from before the update, changing it doesn't seem to be the way to do things

**Comment by darius1702** [comment] 2022-03-23 13:35
Fixed in 12c6a0afef43a533ba52ad09ae9542d8d1c1a2d7,
looks like we didn't have a choice but to change the github action, since apparently it's not a bug but a build-angular-12 (or something) feature

**Closed as completed by darius1702** 2022-03-23 13:35 UTC
